apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-mongodb
  namespace: config-management
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "localhost:27017"
  - name: databaseName
    value: "configdb"
  - name: collectionName
    value: "sessions"
  - name: actorStateStore
    value: "true"